import type { Metadata } from "next";
import { Inter, Nunito_Sans, Prata } from "next/font/google";
import "../globals.css";

import TopBar from "@/components/shared/TopBar";
import NavBarAuth from "@/components/shared/NavBarAuth";
;

const inter = Inter({ subsets: ["latin"] });

const nunitoSans = Nunito_Sans({
    subsets: ['latin'],
    variable: "--font-nunitoSans",
})

const prata = Prata({
    subsets: ['latin'],
    weight: '400',
    variable: "--font-prata",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <TopBar />
        </header>
        <nav >
          <NavBarAuth />
        </nav>
        <main className={`${nunitoSans.variable} ${prata.variable} `}>{children}</main>
      </body>
    </html>
  );
}
